### ISSUE TITLE
Add pattern shift to Groovebox

### ISSUE THREAD

**Issue by spectromas** [clone45/voxglitch#150]
I absolutely love groovebox so thank you for making and sharing it. I don't know why but I have a tendency to write drum beats with the main downbeat not being on the 1. It would be really cool if there was a way to shift the pattern left or right like you can on the Digitakt.

**Comment by clone45** [comment]
Hi spectromas!  You're in luck.  That feature has been implemented and will ship with the next release.  In order to shift tracks, hold the shift-key while dragging one of the blue step buttons left or right.  You might try this right now... I don't know if it's been rolled out or not, but I don't think so.  Thanks!

**Comment by spectromas** [comment]
Fantastic, thank you! Doesn't seem to be in the current version but I'm happy to wait if it is coming. What a beast of a module!
