### ISSUE TITLE
groovebox ctrl+shift+drag 8 tracks drags module

### ISSUE THREAD

**Issue by rasavell** [clone45/voxglitch#180]
Drag 8 tracks doesn't seem to be working on. a mac

**Comment by clone45** [comment]
I've recently heard that, on macs, you may have to press the on/off buttons multiple times for them to work.  I'll be looking into this today!

**Comment by rasavell** [comment]
This was the only problem I found. Cool Module!!

**Comment by clone45** [comment]
Thank you!  I apologize, I misread your bug at first.  If you are trying to scroll through sounds on the Groovebox, there is a known bug with Groovebox on mac where the CTRL+SHIFT+scroll wheel doesn't work.  At the moment, mac users' only means of selecting samples is either:

- double click on a sample slot to select a sample
- right click and use the context menu options to either load a single sample, or the first 8 samples from a folder

I have plans on upgrading the sample selection experience on Groovebox, but it might take some time.  Thanks!

**Comment by rasavell** [comment]
My question was simpler. According to the doc, I think you should be able to Shift+Ctrl to shift all eight patterns at once. But when I use Ctrl= it grabs the modules and scrolls them. Couldn’t find a key combination that worked. 

—>

In order to shift all 8 of the tracks’ data left or right:

Hold down the shift & control keys
Click on one of the blue step buttons
Drag left or right

**Comment by clone45** [comment]
Ah, ok!  It must be related to the other issue, where CONTROL+SHIFT wasn't registering on macs.  I'll have to find a work-around for this.  I'll keep this ticket open until I solve it.  I'll probably have a solution submitted to VCV Rack in about 4 to 5 days.  Thanks for the clarification!

**Comment by rasavell** [comment]
Yes, Shift-Ctrl pans the rack.

https://community.vcvrack.com/t/keyboard-shortcuts/10105/3

**Comment by clone45** [comment]
Ok, no worries.  What I've done is add a menu for shifting all tracks.  I'm aware that this is REALLY tedious, and I'll work to improve this in the future.  I plan on making some major updates to how the track area is utilized on the module.  Instead of just being able to select tracks, that area will act like a generic LCD display, and I'll be able to add features that would normally be difficult to squeeze on to the front panel.  This might take a while, but it's the next project on my list.  Until then, I hope that this solution, even if it's a bit painful, can help.

This will roll out with the next major release (2.22).  Thanks a ton, and sorry for the issues!

![image](https://user-images.githubusercontent.com/1373491/191113335-92532e8d-55f6-43e5-9fff-f26393f218b0.png)

**Comment by rasavell** [comment]
This is not a big deal to me. I was just reporting a bug. But I’m curious from a design perspective. Are all the other key combinations taken up with hotkeys?

**Comment by clone45** [comment]
> But I’m curious from a design perspective. Are all the other key combinations taken up with hotkeys?

My apologies, I'm not quite following your question.  Are you asking if I could use different hotkeys for shifting all sequences left or right?  One of the issues that I've run into with hotkeys is that even if Rack isn't currently utilizing them, there's no guarantee that it won't in the future.

As Squinky Labs said to me once,

> trying to steal keys from VCV is a losing battle (imao).

And sure enough, when version 2 came out, some of my keyboard shortcuts stopped working because Rack decided to use them.  This might get even weirder when using rack as a VST plugin.  One crazy idea I had was to add a "command line" interface to some of my modules, where you could type in commands like "> shift all left 5".

I'm all ears if you have any recommendations!

**Comment by rasavell** [comment]
Yes, that’s what I was asking. And I see what you mean. Since this bug was due to VCV taking the Ctrl-Shift sequence. 
I was asking because I was considering developing some modules. I’m a CS PhD, but I’m getting a bit long in the tooth, and I’ve read some stuff about Andrew that makes me think he’s the kind of guy I left my last two jobs over.

Anyway, not ready to dive in yet. Thought I’d make some music and video for a change instead of just staring at code. But if you need something beta tested, let me know.
Thanks for the chat!

Good luck!
Rob

**Comment by clone45** [comment]
I find it fairly easy to just focus on the positive aspects of module development.   There are definitely some grumpy sounding people on the forums, but they don't get in the way too much.

I've essentially completed the revision of the track and sample section of Groovebox:

![image](https://user-images.githubusercontent.com/1373491/195153284-34331a78-42df-4113-ac35-1ddb24c00a22.png)

Would you be interested in testing this out in a few days?  :-)

Here's how it works:

- Single click on a sample name (or anywhere in the box) to select that track
- Double click on a sample name to pop open the system file selector
- Use the up and down arrows to select the previous or next sample

Cheers,
Bret

**Comment by nay-seven** [comment]
It looks really nice! 
This module gets better every time, bravo!

**Comment by rasavell** [comment]
Sure, I can give it try, if you have a Mac module ready. Sounds cool! 
Also, in case you don’t see it, Omri  says your autobreak studio is “insane!” on his discord.

Bitwig post-apocalypse day 0!!! 

Cheers,
Rob

**Comment by clone45** [comment]
> Also, in case you don’t see it, Omri  says your autobreak studio is “insane!” on his discord.

Oh, wow!!

**Comment by clone45** [comment]
Rob, unfortunately, I'm on PC and don't have a way to create a build for mac, but it shouldn't be too long before it's released.  When it does, I'd love to hear your feedback.  One thing that I'm anxious about is that user would have to know that they can double click on the sample name to load a sample.  It's not obvious by looking at the interface.  However, since there are other ways of loading samples, and since the right-click context menu has instructions on the double-click behavior, it's not so bad.  I was thinking of adding a disk drive icon for opening the file browser, but that might clutter the interface.  

You said,
> Bitwig post-apocalypse day 0!!!

ooooo... I just leaned about this.  Yikes.

**Comment by clone45** [comment]
Hello!  I'm going to close this ticket.  The new groove box module is a lot different and uses context menus instead of shortcut keys.  If there's anything missing, please let me know!
