### ISSUE TITLE
Digital Sequencer not saving CV

### ISSUE THREAD

**Issue by RedstoneParadox** [clone45/voxglitch#182]
Ever since the update, the digital sequencer CVs but not the triggers are reset when closing the patch or maybe re-opening it, it's not clear. The XP version doesn't have this issue.

**Comment by clone45** [comment]
Hello!  Sorry for the late reply.  I've been out of the state and away from my computer for a few days.  The issues that you are having should have been fixed in version 2.21.2.  Could you double check your version number of the Voxglitch modules?  My apologies for that bug.

**Comment by RedstoneParadox** [comment]
I'm currently on 2.21.3.

**Comment by clone45** [comment]
I'm sorry @RedstoneParadox, you are correct.  The bug was still an issue in 2.21.3.  The bugfix that I submitted is still working its way through the VCV Rack build system here: https://github.com/VCVRack/library/projects/1?card_filter_query=voxglitch

I commented on that ticket today to see why it appears to be stalled out.  Hopefully you'll get an updated version within the next few days.

**Comment by clone45** [comment]
This should be fixed and available now, @RedstoneParadox !
