### ISSUE TITLE
Old version of Autobreak with Seq included

### ISSUE THREAD

**Issue by yavaro** [clone45/voxglitch#28]
Hola Bret,
I have a problem; I did a very nice track with your Autobreak with seq included.. but now I cannot open it with the new version... I have download the old version 1.2.1 but Vcvrack says it can find Autobreak.. 
There is a way to use the old version?

Thank you 
Eduardo

**Comment by clone45** [comment]
Hello!  I'm very sorry about that.  I knew that the Autobreak changes may have broken some old patches.  If you are using Windows, I may be able to provide a compiled version for you to drop into your plugins folder?  

Another more sustainable option might go something like this:  If look at your saved patch file using a text editor, you should see the sequencer values stored in that file.  You can then use a 16 step sequencer, such as the Autodafe SEQ16, to recreate the sequence by right-clicking on each of the 16 knobs and setting them to the correct value.

I'm very sorry for the inconvenience.

**Comment by yavaro** [comment]
Hola Bret !! Thank you for your fast answer. Yes, I am using Windows, it would be great if you can compile a version... or if you have two versions of the Autobreak. Also, I miss the tempo knob from the last one, I was using it to 50. Yes I can open it with note pad an read the sequence but what about the tempo... 
Thank you very much!!
Eduardo

**Comment by clone45** [comment]
> Also, I miss the tempo knob from the last one, I was using it to 50. Yes I can open it with note pad an read the sequence but what about the tempo...
Tempo is now controlled via the CLOCK IN input.  In order to get a tempo of 50, you could:
1. Add an Imprompt "Clocked" module to your patch
2. Set the first RATIO to X2
3. Set the BPM to 50
4. Attach the CLK1 output of the Clocked module to the CLOCK IN of Autobreak

![tempo](https://user-images.githubusercontent.com/1373491/75122361-857b2000-5651-11ea-80e3-55ebc127d236.png)

If you'd prefer to use the old version, I zipped up the bundle for you, but it looks like it'll revert all modules back to 1.2.1.  I hope this helps!

[voxglitch_v_1.2.1.zip](https://github.com/clone45/voxglitch/files/4242716/voxglitch_v_1.2.1.zip)

**Comment by yavaro** [comment]
Thank you very much for your help and understanding!!! :)))
All working back!! Thank you for your very nice plugins!!!

I download the old 1.2.1 from the release but it didn't work, why the one you send did it?

Thank you very much
Eduardo

**Comment by bret-2600** [comment]
Of course, my pleasure.  Over this weekend I started taking the old Autobreak sequencer and building a stand-alone module for it.  It's coming along great.  I expect to have it released in about a week. :-)

**Comment by clone45** [comment]
Of course, my pleasure. Over this weekend I started taking the old Autobreak sequencer and building a stand-alone module for it. It's coming along great. I expect to have it released in about a week. :-)
