### ISSUE TITLE
Suggestions about new digital sequencer

### ISSUE THREAD

**Issue by nay-seven** [clone45/voxglitch#33]
Hello, 
Thanks a lot for this new module !
2 suggestions:
a draw mode for the gate sequencer ? same as the values one, can be useful to create all step speeder?
A way to choice voltage output ? -5/5, -10/10, 0/10 or maybe better  2 range knobs ? min/max

**Comment by clone45** [comment]
I like these ideas.  

>a draw mode for the gate sequencer

For the gate sequencer draw mode, I love the idea but I have a question on how that might work.  If you have a gate sequence such as:

1 0 0 0 1 1 1 0 0 0

.. And you click on the first "1" and start dragging to the right, should it set all the values you drag over to "0"?  I think so, but just wanted to get your opinion.  I agree that this is a good idea and should have it done within the next few days.

> A way to choice voltage output ? -5/5, -10/10, 0/10 or maybe better 2 range knobs ? min/max

I'll see what I can do.  If I can pull it off, I'll probably add the range options in the right-click context menu.  It's tricky to do only because of the way that nudge functionality works. 

PS: If you didn't know, you can shift the sequencer left and right using the left and right arrow keys.  you can "nudge" values up and down using the up and down arrow keys.

I'll leave this ticket open and try to implement your suggestion within about a week.  Thanks!!

**Comment by nay-seven** [comment]
glad you like them ! 
yes about the draw mode and thanks for the arrow tips, useful !

**Comment by clone45** [comment]
@nay-seven I've implemented draw mode for triggers!  I've submitted the update to the user library so it should be available within a few days.  Output ranges may take a while.

**Comment by nay-seven** [comment]
I have buid it ( Mac) , works fine, thanks a lot !!

**Comment by paulrobertpine** [comment]
Just want to say thank you for the sequencer, it's the best!

**Comment by clone45** [comment]
@paulrobertpine You are very welcome!  I'm glad that you like it!

**Comment by clone45** [comment]
@nay-seven I've added per-sequence voltage range selection to the context menu in the most recent build.  It's currently on the master branch.  This will be submitted to the VCV Rack library in the next release (1.8.0) probably by the end of tomorrow.

**Comment by nay-seven** [comment]
Whaou ! and each sequence has its own range ! perfect !
Thanks a lot Bret ! Great modulation engine !

**Comment by clone45** [comment]
@nay-seven You're welcome!  I'm planning on doing some work on the visualization of negative voltages which you can see here: https://community.vcvrack.com/t/voxglitch-modules-beta-testers-welcome/7458/179.  I'll close this ticket, but I'll try and complete that feature soon!
